import { useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowUpRight, Eye, EyeOff, BookOpen, ShieldCheck } from 'lucide-react';

export default function DocsPage() {
  const { hash } = useLocation();
  useEffect(() => { if (hash) document.getElementById(hash.slice(1))?.scrollIntoView(); }, [hash]);
  return <div className="page-shell">
    <header className="page-heading"><span className="section-kicker">The Cairn field guide</span><h1>Know what you share.</h1><p>A practical guide to invitations, private witnesses, and the public trail a proof leaves behind.</p></header>
    <div className="docs-grid page-section-tight">
      <aside className="docs-nav" aria-label="On this page"><span>In this guide</span><a href="#idea">The idea</a><a href="#start">Get started</a><a href="#privacy">Privacy & limits</a><a href="#contract">Under the surface</a><a href="#levels">Launch checklist</a></aside>
      <div className="docs-content">
        <section id="idea"><BookOpen className="section-icon" size={25} aria-hidden="true" /><h2>Private allowlist access, kept small.</h2><p>Cairn gives invitation-only communities a way to verify access without collecting identity details. An organizer issues a secret and a clearance level. A member proves those credentials match the active invitation and satisfy the gate’s rules. The public outcome is a one-time badge, not a member profile.</p><p>This MVP has <strong>one active invitation commitment per gate</strong>. After an invitation is used, the organizer can rotate to the next one. It is not a Merkle-tree allowlist, an identity provider, or proof that one wallet equals one human.</p></section>
        <section id="start"><h2>Your first trip through.</h2><ol className="guide-steps"><li><strong>Choose your network.</strong><p>The admin portal starts on Preview. Use Preprod for the Level 2–4 deployment. Connect a compatible Midnight Lace, 1AM, or Nightly wallet with DUST available.</p></li><li><strong>Create and back up an invitation.</strong><p>Set a gate label, minimum clearance, issued clearance, and capacity. Keep the administrator secret offline. Share only the member invitation with the intended recipient.</p></li><li><strong>Deploy from the browser.</strong><p>Approve the wallet request. Submission and indexer confirmation are separate steps. The address becomes active for the chosen network without a rebuild.</p></li><li><strong>Use the invitation.</strong><p>Open Your invitation, enter the secret and its exact issued clearance, then approve the proof transaction. A reused invitation is rejected.</p></li><li><strong>Check the public badge.</strong><p>Download the receipt and look up its badge in the Registry. A verifier does not need your secret or a wallet.</p></li></ol><Link className="button button-primary" to="/admin">Open the deployment portal <ArrowUpRight size={17} aria-hidden="true" /></Link></section>
        <section id="privacy"><h2>The privacy boundary.</h2><div className="privacy-doc-columns"><div><EyeOff size={23} aria-hidden="true" /><h3>Not written to the ledger</h3><ul><li>The 32-byte invitation secret.</li><li>The member’s exact issued clearance.</li><li>The administrator secret used for policy changes.</li></ul></div><div><Eye size={23} aria-hidden="true" /><h3>Public by design</h3><ul><li>Gate label, active commitment, threshold, capacity and open state.</li><li>Number of entries, nullifiers and badge commitments.</li><li>Administrator commitment and transaction activity.</li></ul></div></div><h3>What a proof does not promise</h3><p>The invitation is a bearer credential: someone who copies it can race its owner to use it. A badge’s presence proves registration, not ownership or a real-world identity. Badge receipts are transferable. The administrator knows which invitation they issued.</p><p>The nullifier is deterministic from the secret. Reusing a secret across gates can link those entries; always issue fresh cryptographically random secrets. Transaction timing, fee/payment metadata, your wallet, indexer, network provider and any remote proving service may enable correlation. This application does not claim complete anonymity.</p><p>Witnesses stay out of the public ledger, but a configured proving service may process private proof material. Use a trusted or local proof server. Browser memory is not a hardware vault; extensions, a compromised device, and malicious scripts are outside this MVP’s protection.</p></section>
        <section id="contract"><h2>Small contract. Explicit decisions.</h2><p><code>contracts/cairn.compact</code> supplies three state-changing circuits. The source is compiled into generated JavaScript, ZKIR and proving/verifying keys. The browser serves the keys from <code>/managed</code>.</p><div className="circuit-list"><div><code>prove_access</code><p>Checks the private secret and bound clearance, the threshold, capacity, open state and replay protection; inserts a badge and nullifier.</p></div><div><code>update_gate</code><p>Authenticates the private administrator witness, then rotates the invitation commitment and policy.</p></div><div><code>set_gate_open</code><p>Authenticates the administrator and pauses or reopens admissions.</p></div></div><p><code>disclose()</code> marks intentional public values. Clearance is included in the invitation commitment, so changing the supplied level invalidates the credential rather than bypassing the threshold.</p><h3>Run locally</h3><pre className="code-block"><code>{`npm ci
npm ci --prefix frontend
npm run compile
npm test
npm run build
npm run dev --prefix frontend`}</code></pre><p>Use Node 22 and Compact 0.31.x. Windows uses WSL for the Compact compiler, not Windows’ unrelated <code>compact.exe</code>. See the root README and <code>docs/SETUP.md</code> for toolchain configuration and optional Docker-backed tests.</p></section>
        <section id="levels"><ShieldCheck className="section-icon" size={25} aria-hidden="true" /><h2>Built for the journey. Not a claim of completion.</h2><p>The source, circuits, browser flows, automated tests, workflow and documentation support Levels 1–4. Passing a level also needs evidence that cannot be manufactured by the app.</p><ul><li><strong>Level 1:</strong> a real Preview or Preprod deployment, compile/deployment screenshots and at least 5 meaningful commits.</li><li><strong>Level 2:</strong> a verifiable Preprod address, live frontend, Lace connect/disconnect and successful circuit-call recording, and at least 8 commits.</li><li><strong>Level 3:</strong> passing hosted CI runs, an approved Private Allowlist Access proposal, a full-flow demo, and at least 10 commits.</li><li><strong>Level 4:</strong> a live Preprod MVP, complete public docs, a real product X profile linked in the README, a demo video and at least 15 commits.</li></ul><p>The full evidence matrix is in <code>docs/LEVELS.md</code>. No old contract address, demo, repository, social profile or fabricated badge is carried into Cairn.</p></section>
      </div>
    </div>
  </div>;
}
